services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "INTERNAL://kafka:9092,EXTERNAL://kafka:29092,CONTROLLER://kafka:9093"
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true" 
      KAFKA_CFG_NUM_PARTITIONS: "3" 
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - backend

  cassandra1:
    image: bitnami/cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - ./init-scripts/cassandra:/docker-entrypoint-initdb.d:ro
    environment:
      CASSANDRA_CLUSTER_NAME: "bus_cluster"
      CASSANDRA_SEEDS: "192.168.1.101"
      CASSANDRA_LISTEN_ADDRESS: "192.168.1.101"
      CASSANDRA_BROADCAST_ADDRESS: "192.168.1.101"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_PASSWORD_SEEDER: "yes"
    networks:
      - backend

  ingestor:
    build:
      context: ./ingestor
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      cassandra1:
        condition: service_started
    env_file:
      - .env
    environment:
      KAFKA_BROKER: "kafka:9092"
      CASSANDRA_HOST: "cassandra1"
      CASSANDRA_DC: "datacenter1"
      KAFKA_TOPIC: "bus-locations"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
